import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  flex`}
      >
        <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger />
          <div className="flex bg-gray-200 p-4 m-4 w-full flex-col rounded-2xl max-h-[calc(100vh-2rem)]">
            <div className="flex  w-full flex-col">
              <div className="flex  w-full flex-col">{children}</div>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
